# Generated by Django 5.0.6 on 2024-06-12 16:59

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_generator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerarygenerator',
            name='day',
        ),
        migrations.RemoveField(
            model_name='itinerarygenerator',
            name='plan',
        ),
        migrations.AddField(
            model_name='itinerarygenerator',
            name='api_response',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
