# Generated by Django 5.0.6 on 2024-06-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_generator', '0002_remove_itinerarygenerator_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarygenerator',
            name='days',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
